# frozen_string_literal: true

source 'https://rubygems.org'

gem 'allure-rspec', '~>0.8.0'
gem 'headless'
gem 'parallel_tests', group: [:development, :test]
gem 'rspec'
gem 'ruby-gmail', '~> 0.3.1'
gem 'selenium-webdriver', '~> 2.44.0'
